create table scheduler_job
(
    id              integer generated by default as identity
        constraint scheduler_job_pkey
            primary key,
    job_name        varchar(255)         not null,
    job_group       varchar(255)         not null,
    job_class       varchar(255)         not null,
    cron_expression varchar(255)         not null,
    start_time      varchar(255)         not null,
    repeat_time     numeric              not null,
    cron_job        boolean default true not null,
    invoke_param    varchar(255)         not null,
    repeat_count    integer default 0    not null
);

create table scheduler_job_history
(
    id          integer generated by default as identity
        constraint scheduler_job_history_pkey
            primary key,
    job_name    varchar(255) not null,
    start_time  varchar(255),
    end_time    varchar(255),
    last_run    bigint,
    status      varchar(255),
    exit_status varchar(255),
    details     varchar(255)
);
